SuperheroCreator/Models/ErrorViewModel.cs
using System;

namespace SuperheroCreator.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SuperheroCreator/Models/Superhero.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SuperheroCreator.Models
{
    public class Superhero
    {
        [Key]
        public int SuperheroId { get; set; }
        public string HeroName { get; set; }

        public string CivilianName { get; set; }

        public string PrimaryAbility { get; set; }

        public string SecondaryAbility { get; set; }

        public string CatchPhrase { get; set; }
    }
}

SuperheroCreator/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SuperheroCreator.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SuperheroCreator.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SuperheroCreator/Controllers/SuperheroController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SuperheroCreator.Models;
using SuperheroCreator.Data;

namespace SuperheroCreator.Controllers
{
    public class SuperheroController : Controller
    {

        private readonly ApplicationDbContext _context;

        public SuperheroController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: SuperheroController
        public ActionResult Index()
        {
            var superhero = _context.Superheroes;
            return View(superhero);

        }

        // GET: SuperheroController/Details/5
        public ActionResult Details(int id)
        {
            Superhero superhero = _context.Superheroes.FirstOrDefault(i => i.SuperheroId == id);
            return View(superhero);
        }

        // GET: SuperheroController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SuperheroController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Superhero superhero)
        {
            try
            {
                _context.Add(superhero);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SuperheroController/Edit/5
        public ActionResult Edit(int id)
        {
            Superhero superhero = _context.Superheroes.Single(i => i.SuperheroId == id);
            return View(superhero);
        }

        // POST: SuperheroController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Superhero superhero)
        {
            try
            {
                _context.Superheroes.Update(superhero);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SuperheroController/Delete/5
        public ActionResult Delete(int id)
        {
            Superhero superhero = _context.Superheroes.Single(i => i.SuperheroId == id);
            return View(superhero);
        }

        // POST: SuperheroController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Superhero superhero)
        {
            try
            {
                _context.Remove(superhero);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

SuperheroCreator/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<hr />
<div class="text-center">
    <h1 class="display-4" style="margin-bottom: 5%; text-shadow: 5px 5px 5px orange;">Superheroes, Welcome!</h1>
    <hr />
    <div class="row">
        <h5 class="col-md-6">Create Hero</h5>
        <h5 class="col-md-6">View Hero Database</h5>
    </div>
    <div class="row" style="margin-top: 4%;">
        <div class="col-md-6">
            <a asp-area="" asp-controller="Superhero" asp-action="Create">
                <img style="width: 16%; height: auto;" src="/images/hammer-cartoon-vector-1036743.jpg" alt="picture of construction hammer." />
            </a>
        </div>
        <div class="col-md-6">
            <a asp-area="" asp-controller="Superhero" asp-action="Index">
                <img style="width: 30%; height: auto;" src="/images/book_image.jpeg" alt="picture of hard-covered text." />
            </a>
        </div>
    </div>
</div>


<hr />

<img style="margin-top: 25%; width: 100%; height: auto;" src="/images/heroInCityWithBook.png" />

SuperheroCreator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SuperheroCreator</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-cyborg.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <img src="/images/superhero_explosion2.png" style="width: 100%;" />
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <a style="transition-duration: .4s;" class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Superhero Creator</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                            Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Hero Database</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" asp-area="" asp-controller="Superhero" asp-action="Create">Create Hero</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Superhero" asp-action="Index">View Heroes</a>
                            @*<div class="dropdown-divider"></div>*@
                            @*<a class="dropdown-item" href="#">Separated link</a>*@
                        </div>
                    </li>
                </ul>
                @*<form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="text" placeholder="Search">
                    <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                </form>*@
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SuperheroCreator - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>



@*<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SuperheroCreator</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
            <partial name="_LoginPartial" />
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Superhero" asp-action="Create">Create Hero</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Superhero" asp-action="Index">View Heroes</a>
                </li>
            </ul>
        </div>
    </div>
</nav>*@

SuperheroCreator/Views/Superhero/Create.cshtml
@model SuperheroCreator.Models.Superhero

@{
    ViewData["Title"] = "Create";
}



<hr />
<h1>Superhero</h1>
<h4>Creation</h4>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="HeroName" class="control-label">Hero Name</label>
                <input asp-for="HeroName" class="form-control" />
                <span asp-validation-for="HeroName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CivilianName" class="control-label">Civilian Name</label>
                <input asp-for="CivilianName" class="form-control" />
                <span asp-validation-for="CivilianName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrimaryAbility" class="control-label">Primary Power</label>
                <input asp-for="PrimaryAbility" class="form-control" />
                <span asp-validation-for="PrimaryAbility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SecondaryAbility" class="control-label">Secondary Power</label>
                <input asp-for="SecondaryAbility" class="form-control" />
                <span asp-validation-for="SecondaryAbility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CatchPhrase" class="control-label">Catch Phrase</label>
                <input asp-for="CatchPhrase" class="form-control" />
                <span asp-validation-for="CatchPhrase" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SuperheroCreator/Views/Superhero/Delete.cshtml
@model SuperheroCreator.Models.Superhero

@{
    ViewData["Title"] = "Delete";
}


<hr />
<h3>Are you sure you want to delete this superhero?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HeroName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HeroName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CivilianName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CivilianName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrimaryAbility)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrimaryAbility)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SecondaryAbility)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SecondaryAbility)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CatchPhrase)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CatchPhrase)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="SuperheroId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SuperheroCreator/Views/Superhero/Details.cshtml
@model SuperheroCreator.Models.Superhero

@{
    ViewData["Title"] = "Details";
}

<hr />

<h1>@Html.DisplayFor(model => model.HeroName)</h1>

<div>
    <h4>Bio</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Hero Name
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HeroName)
        </dd>
        <dt class = "col-sm-2">
            Civilian Name
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CivilianName)
        </dd>
        <dt class = "col-sm-2">
            Primary Power
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrimaryAbility)
        </dd>
        <dt class = "col-sm-2">
            Secondary Power
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SecondaryAbility)
        </dd>
        <dt class = "col-sm-2">
            Catchphrase
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CatchPhrase)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.SuperheroId">Edit</a> |
    <a asp-action="Delete" asp-route-id="@Model.SuperheroId">Delete</a> |
    <a asp-action="Index">Back to List</a>
</div>

SuperheroCreator/Views/Superhero/Edit.cshtml
@model SuperheroCreator.Models.Superhero

@{
    ViewData["Title"] = "Edit";
}

<hr />
<h1>Edit</h1>

<h4>Superhero</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="SuperheroId" />
            <div class="form-group">
                <label asp-for="HeroName" class="control-label">Hero Name</label>
                <input asp-for="HeroName" class="form-control" />
                <span asp-validation-for="HeroName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CivilianName" class="control-label">Civilian Name</label>
                <input asp-for="CivilianName" class="form-control" />
                <span asp-validation-for="CivilianName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrimaryAbility" class="control-label">Primary Power</label>
                <input asp-for="PrimaryAbility" class="form-control" />
                <span asp-validation-for="PrimaryAbility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SecondaryAbility" class="control-label">Secondary Power</label>
                <input asp-for="SecondaryAbility" class="form-control" />
                <span asp-validation-for="SecondaryAbility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CatchPhrase" class="control-label">Catch Phrase</label>
                <input asp-for="CatchPhrase" class="form-control" />
                <span asp-validation-for="CatchPhrase" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SuperheroCreator/Views/Superhero/Index.cshtml
@model IEnumerable<SuperheroCreator.Models.Superhero>

@{
    ViewData["Title"] = "Index";
}

<hr />
<h1 style="text-align: center;">The Official Superhero Database</h1>
<hr />

<table class="table" style="text-align: center; border-bottom: 1px solid #dee2e6;">
    <thead>
        <tr>
            <th>
                Hero Name
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td style="border-bottom: 1px solid #dee2e6;"><a asp-action="Create">Create New Hero</a></td>
        </tr>
@foreach (var item in Model) {
        <tr>
            <td style="border-top: none;">
                <a style="color: white;" asp-action="Details" asp-route-id="@item.SuperheroId">@item.HeroName</a>
            </td>
        </tr>
}
    </tbody>
</table>